---
# tasks file for golem-dev-linux


- name: Install docker-ce dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - curl


- name: Install docker-ce key
  apt_key:
    url: "{{ docker_ce_repository_key_url }}"


- debug:
    msg: "TODO purge all other docker repositories"


- name: Add docker repo, 64bit ONLY!
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_ce_repository_url }} {{ ansible_lsb['codename'] }} stable"


- name: Install docker-ce
  apt:
    name: docker-ce
    update_cache: yes


- name: Add GETH repo
  apt_repository:
    repo: "{{ geth_repository }}"


- name: Install GETH
  apt:
    name: ethereum
    update_cache: yes

- name: setup buildbot-worker user
  user:
    name: "{{ buildbot_user }}"
    group: "{{ buildbot_group }}"
    groups:
      - docker
    home: "{{ buildbot_user_homedir }}"

- name: Install taskcollector dependencies
  apt:
    name: "{{item}}"
  with_items:
    - gcc-5
    - g++-5
    - libfreeimage3
    - libfreeimage-dev


- name: Prepare hyperg directory
  file:
    dest: "{{ hyperg_base_dir }}"
    state: directory


- name: Install hyperg
  unarchive:
    src: "{{ hyperg_package_url }}"
    dest: "{{ hyperg_base_dir }}"
    remote_src: yes
  args:
    creates: "{{ hyperg_install_dir }}"


- name: Link hyperg
  file:
    src: "{{ hyperg_install_dir}}/hyperg"
    dest: "{{ hyperg_link_target_dir }}/hyperg"
    state: link


- name: Add python 3.6 repo
  apt_repository:
    repo: "ppa:jonathonf/python-3.6"
    update_cache: yes


- name: install golemapp dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - python3.6
    - python3.6-dev
    - openssl
    - pkg-config
    - libjpeg-dev
    - libopenexr-dev
    - libssl-dev
    - autoconf
    - libgmp-dev
    - libtool
    - libffi-dev
    - libgtk2.0-0
    - libxss1
    - libgconf-2-4
    - libnss3
    - libasound2
